language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pylint

services:
  - mysql

before_script:
  - mysql -u root -e 'CREATE DATABASE testbase;'

env:
  - MYSQL_DB_USER="root" MYSQL_DB_PASSWORD="" MYSQL_DB_HOST="127.0.0.1" MYSQL_DB_DATABASE="testbase"

script:
  - pylint department_app
  - coverage run -m unittest discover -s department_app/tests

after_success:
  - coveralls