language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pylint

script:
  - pylint department_app
  - coverage run -m pytest